FROM cgr.dev/chainguard/wolfi-base:latest

MAINTAINER Paul Novarese <pvn@novarese.net>
LABEL maintainer="pvn@novarese.net"
LABEL name="anchore-tools-experimental"
LABEL org.opencontainers.image.title="anchore-tools-experimental"
LABEL org.opencontainers.image.description="EXPERIMENTAL PROTOTYPE anchore command line scanning tools (syft, grype, and anchorectl)"

HEALTHCHECK --timeout=10s CMD /bin/true || exit 1

# Installing required packages
RUN apk add --no-cache --upgrade \
    curl \
    grep \
    jq \
    bash \
    git \
    && curl -sSfL https://anchorectl-releases.anchore.io/anchorectl/install.sh | sh -s -- -b /usr/local/bin v1.8.0 \
    && curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin v0.84.1 \
    && curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin v0.63.1 \
    && mkdir -p /home \
    && addgroup -g 1000 anchore \
    && adduser -u 1000 -G anchore --shell /bin/bash -D -h /home/anchore anchore \
    && chmod 0755 /home/anchore

# ensure we have a unique build and also provide a little metadata
RUN date > /image_build_timestamp && \
    touch image_build_timestamp_$(date +%Y-%m-%d_%T)
    
# Setting WORKDIR and USER 
USER anchore 
WORKDIR /home/anchore

CMD ["/bin/bash"]
